project:
  type: book
  output-dir: doc

book:
  title: "R Coding: Good to Know"
  author: "Thiyanga S. Talagala"
  date: "2026"
  chapters:
    - index.qmd
    - intro.qmd
    - purrr.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

